// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RepositoryContext.Entity_FRamework;

#nullable disable

namespace RepositoryContext.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240114010312_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Auteur")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Auteur = "Alice",
                            Contenu = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eget laoreet felis, fermentum porta metus. Suspendisse a dapibus ante. Donec ex purus, sagittis dignissim elit sed, vehicula iaculis lacus. Praesent pretium porta felis. In porttitor leo metus, a tristique tortor convallis eu. Nam luctus lacus eget commodo lobortis. Vestibulum at fermentum tortor, ut volutpat arcu.\r\n\r\nPraesent dictum quam sit amet rutrum consectetur. Curabitur quam quam, mollis ac luctus eu, laoreet vel nunc. Suspendisse vel elit odio. Aenean pharetra sed nisi ut mollis. Fusce eu nisl feugiat, eleifend nisi et, rutrum nunc. Nunc volutpat ante at ligula condimentum blandit. Morbi dapibus, nunc id suscipit mattis, mauris felis blandit lacus, ac tincidunt risus ipsum id nunc. In posuere leo id lectus laoreet elementum. ",
                            DateCreation = new DateTime(2024, 1, 14, 2, 3, 11, 860, DateTimeKind.Local).AddTicks(5312),
                            DateModification = new DateTime(2024, 1, 14, 2, 3, 11, 860, DateTimeKind.Local).AddTicks(5392),
                            Theme = "Lorem Ipsum"
                        },
                        new
                        {
                            Id = 2,
                            Auteur = "Otis",
                            Contenu = "Vous savez, moi je ne crois pas qu’il y ait de bonne ou de mauvaise situation. Moi, si je devais résumer ma vie aujourd’hui avec vous, je dirais que c’est d’abord des rencontres. Des gens qui m’ont tendu la main, peut-être à un moment où je ne pouvais pas, où j’étais seul chez moi. Et c’est assez curieux de se dire que les hasards, les rencontres forgent une destinée… Parce que quand on a le goût de la chose, quand on a le goût de la chose bien faite, le beau geste, parfois on ne trouve pas l’interlocuteur en face je dirais, le miroir qui vous aide à avancer. Alors ça n’est pas mon cas, comme je disais là, puisque moi au contraire, j’ai pu : et je dis merci à la vie, je lui dis merci, je chante la vie, je danse la vie… je ne suis qu’amour ! Et finalement, quand beaucoup de gens aujourd’hui me disent « Mais comment fais-tu pour avoir cette humanité ? », et bien je leur réponds très simplement, je leur dis que c’est ce goût de l’amour ce goût donc qui m’a poussé aujourd’hui à entreprendre une construction mécanique, mais demain qui sait ? Peut-être simplement à me mettre au service de la communauté, à faire le don, le don de soi…",
                            DateCreation = new DateTime(2024, 1, 9, 2, 3, 11, 860, DateTimeKind.Local).AddTicks(5399),
                            DateModification = new DateTime(2024, 1, 12, 2, 3, 11, 860, DateTimeKind.Local).AddTicks(5403),
                            Theme = "Situation des scribes"
                        },
                        new
                        {
                            Id = 3,
                            Auteur = "Criquette",
                            Contenu = "Le WQT est un animal aquatique nocturne",
                            DateCreation = new DateTime(2023, 11, 14, 2, 3, 11, 860, DateTimeKind.Local).AddTicks(5405),
                            DateModification = new DateTime(2023, 12, 27, 2, 3, 11, 860, DateTimeKind.Local).AddTicks(5410),
                            Theme = "WQT"
                        });
                });

            modelBuilder.Entity("Entities.Commentaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<string>("Auteur")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("Commentaires");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArticleId = 1,
                            Auteur = "Bob",
                            Contenu = "Lorem lorem",
                            DateCreation = new DateTime(2024, 1, 14, 2, 3, 11, 860, DateTimeKind.Local).AddTicks(5417),
                            DateModification = new DateTime(2024, 1, 14, 2, 3, 11, 860, DateTimeKind.Local).AddTicks(5419)
                        },
                        new
                        {
                            Id = 2,
                            ArticleId = 2,
                            Auteur = "Asterix",
                            Contenu = "C'est une autre culture",
                            DateCreation = new DateTime(2024, 1, 14, 2, 3, 11, 860, DateTimeKind.Local).AddTicks(5424),
                            DateModification = new DateTime(2024, 1, 14, 2, 3, 11, 860, DateTimeKind.Local).AddTicks(5426)
                        },
                        new
                        {
                            Id = 3,
                            ArticleId = 3,
                            Auteur = "Brett",
                            Contenu = "Je vous crois",
                            DateCreation = new DateTime(2024, 1, 14, 2, 3, 11, 860, DateTimeKind.Local).AddTicks(5428),
                            DateModification = new DateTime(2024, 1, 14, 2, 3, 11, 860, DateTimeKind.Local).AddTicks(5430)
                        });
                });

            modelBuilder.Entity("Entities.Commentaire", b =>
                {
                    b.HasOne("Entities.Article", "Article")
                        .WithMany("Comments")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("Entities.Article", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
